# Generated by Django 4.2.8 on 2023-12-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_elementary_galleries_juniorhigh_galleries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=100)),
                ('tuition', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.CharField(max_length=30)),
            ],
        ),
    ]
