# Generated by Django 4.2.8 on 2023-12-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_school_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honor_roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('school', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=30)),
            ],
        ),
    ]
