# Generated by Django 4.2.8 on 2023-12-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_honor_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30)),
                ('totalschool_in_words', models.CharField(max_length=100)),
                ('totalschool_in_num', models.IntegerField()),
                ('totalstudent_in_word', models.CharField(max_length=100)),
                ('totalstudent_in_num', models.IntegerField()),
                ('year_of_service_in_word', models.CharField(max_length=100)),
                ('year_of_service_in_num', models.IntegerField()),
                ('total_alumni_in_word', models.CharField(max_length=100)),
                ('total_alumi_in_num', models.IntegerField()),
            ],
        ),
    ]
