# Generated by Django 4.2.8 on 2023-12-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_totalstudent_in_word_statistics_totalstudent_in_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutmcss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
