# Generated by Django 4.2.8 on 2023-12-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_aboutmcss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formersups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
