# Generated by Django 4.2.8 on 2023-12-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_council_sr_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmcss',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='aboutmcss',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
