# Generated by Django 4.2.8 on 2024-03-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
